# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Notes
tagline:          'some tagline'
description:      'A personal space for Notes, thoughts, ideas and more'
baseurl:          /

# Collections for your notes
collections:
  thoughts:
    output: true
    permalink: /thoughts/:title/
  films:
    output: true
    permalink: /films/:title/
  pages:
    output: true
    permalink: /pages/:title/
